// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PLATFORM_API_G_H_
#define PIGEON_PLATFORM_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class PlatformApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class GetPlatformTypeRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  GetPlatformTypeRequest();

  // Constructs an object setting all fields.
  explicit GetPlatformTypeRequest(const int64_t* test_param);

  const int64_t* test_param() const;
  void set_test_param(const int64_t* value_arg);
  void set_test_param(int64_t value_arg);


 private:
  static GetPlatformTypeRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::optional<int64_t> test_param_;

};


// Generated class from Pigeon that represents data sent in messages.
class GetPlatformTypeResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  GetPlatformTypeResponse();

  // Constructs an object setting all fields.
  explicit GetPlatformTypeResponse(const std::string* platform_type);

  const std::string* platform_type() const;
  void set_platform_type(const std::string_view* value_arg);
  void set_platform_type(std::string_view value_arg);


 private:
  static GetPlatformTypeResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::optional<std::string> platform_type_;

};

class PigeonCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonCodecSerializer();
  inline static PigeonCodecSerializer& GetInstance() {
    static PigeonCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PlatformApi {
 public:
  PlatformApi(const PlatformApi&) = delete;
  PlatformApi& operator=(const PlatformApi&) = delete;
  virtual ~PlatformApi() {}
  virtual ErrorOr<GetPlatformTypeResponse> GetPlatformType(const GetPlatformTypeRequest& request) = 0;

  // The codec used by PlatformApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PlatformApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PlatformApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PlatformApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  PlatformApi() = default;

};
}  // namespace vpn_plugin
#endif  // PIGEON_PLATFORM_API_G_H_
