// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "platform_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// GetPlatformTypeRequest

GetPlatformTypeRequest::GetPlatformTypeRequest() {}

GetPlatformTypeRequest::GetPlatformTypeRequest(const int64_t* test_param)
 : test_param_(test_param ? std::optional<int64_t>(*test_param) : std::nullopt) {}

const int64_t* GetPlatformTypeRequest::test_param() const {
  return test_param_ ? &(*test_param_) : nullptr;
}

void GetPlatformTypeRequest::set_test_param(const int64_t* value_arg) {
  test_param_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void GetPlatformTypeRequest::set_test_param(int64_t value_arg) {
  test_param_ = value_arg;
}


EncodableList GetPlatformTypeRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(test_param_ ? EncodableValue(*test_param_) : EncodableValue());
  return list;
}

GetPlatformTypeRequest GetPlatformTypeRequest::FromEncodableList(const EncodableList& list) {
  GetPlatformTypeRequest decoded;
  auto& encodable_test_param = list[0];
  if (!encodable_test_param.IsNull()) {
    decoded.set_test_param(encodable_test_param.LongValue());
  }
  return decoded;
}

// GetPlatformTypeResponse

GetPlatformTypeResponse::GetPlatformTypeResponse() {}

GetPlatformTypeResponse::GetPlatformTypeResponse(const std::string* platform_type)
 : platform_type_(platform_type ? std::optional<std::string>(*platform_type) : std::nullopt) {}

const std::string* GetPlatformTypeResponse::platform_type() const {
  return platform_type_ ? &(*platform_type_) : nullptr;
}

void GetPlatformTypeResponse::set_platform_type(const std::string_view* value_arg) {
  platform_type_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void GetPlatformTypeResponse::set_platform_type(std::string_view value_arg) {
  platform_type_ = value_arg;
}


EncodableList GetPlatformTypeResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(platform_type_ ? EncodableValue(*platform_type_) : EncodableValue());
  return list;
}

GetPlatformTypeResponse GetPlatformTypeResponse::FromEncodableList(const EncodableList& list) {
  GetPlatformTypeResponse decoded;
  auto& encodable_platform_type = list[0];
  if (!encodable_platform_type.IsNull()) {
    decoded.set_platform_type(std::get<std::string>(encodable_platform_type));
  }
  return decoded;
}


PigeonCodecSerializer::PigeonCodecSerializer() {}

EncodableValue PigeonCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129:
      return CustomEncodableValue(GetPlatformTypeRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(GetPlatformTypeResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(GetPlatformTypeRequest)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<GetPlatformTypeRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(GetPlatformTypeResponse)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<GetPlatformTypeResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by PlatformApi.
const flutter::StandardMessageCodec& PlatformApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonCodecSerializer::GetInstance());
}

// Sets up an instance of `PlatformApi` to handle messages through the `binary_messenger`.
void PlatformApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  PlatformApi* api) {
  PlatformApi::SetUp(binary_messenger, api, "");
}

void PlatformApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  PlatformApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getPlatformType" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const GetPlatformTypeRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<GetPlatformTypeResponse> output = api->GetPlatformType(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue PlatformApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue PlatformApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace vpn_plugin
