# Without FVM

gen:
	@echo "* Generate pigeon *"
	@dart pub run pigeon --input pigeons/platform_api.dart --swift_out ios/Classes/PlatformApi.g.swift
	@dart pub run pigeon --input pigeons/platform_api.dart --swift_out macos/Classes/PlatformApi.g.swift