// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetPlatformTypeRequest {
  var testParam: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> GetPlatformTypeRequest? {
    let testParam: Int64? = isNullish(__pigeon_list[0]) ? nil : (__pigeon_list[0] is Int64? ? __pigeon_list[0] as! Int64? : Int64(__pigeon_list[0] as! Int32))

    return GetPlatformTypeRequest(
      testParam: testParam
    )
  }
  func toList() -> [Any?] {
    return [
      testParam
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetPlatformTypeResponse {
  var platformType: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> GetPlatformTypeResponse? {
    let platformType: String? = nilOrValue(__pigeon_list[0])

    return GetPlatformTypeResponse(
      platformType: platformType
    )
  }
  func toList() -> [Any?] {
    return [
      platformType
    ]
  }
}
private class PlatformApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GetPlatformTypeRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return GetPlatformTypeResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GetPlatformTypeRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? GetPlatformTypeResponse {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformApiPigeonCodecWriter(data: data)
  }
}

class PlatformApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PlatformApiPigeonCodec(readerWriter: PlatformApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlatformApi {
  func getPlatformType(request: GetPlatformTypeRequest) throws -> GetPlatformTypeResponse
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApiPigeonCodec.shared }
  /// Sets up an instance of `PlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformTypeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.PlatformApi.getPlatformType\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformTypeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GetPlatformTypeRequest
        do {
          let result = try api.getPlatformType(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformTypeChannel.setMessageHandler(nil)
    }
  }
}
