name: tray_manager
version: 0.1.1-pre.1
publish_to: 'none'

resolution: workspace

description: "TrustTunnel macOS and Windows system tray API and menu models."

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: TrayManagerMacosPlugin
      windows:
        pluginClass: TrayManagerPluginCApi