name: Flutter Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  resolve-runner:
    runs-on: [team-flutter]
    outputs:
      image: ${{ steps.kv.outputs.value }}
    steps:
      - uses: AdGuardSoftwareLimited/actions/actions/kv-get@master
        id: kv
        with:
          key: build-images/macos

  lint:
    needs: [resolve-runner]
    runs-on:
      - ephemeral
      - ephemeral-mac
      - ${{ needs.resolve-runner.outputs.image }}
      - ephemeral-limit-memory-5120
      - ephemeral-limit-cpu-2
      - ephemeral-limit-disk-gb-20
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Apply PR overrides
        uses: AdGuardSoftwareLimited/actions/actions/apply-pr-overrides@master

      - name: initialize project
        run: make init

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze